AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order State Machine API

Globals:
  Api:
    Cors:
      AllowMethods: "'POST,GET,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 15
    MemorySize: 512
    Runtime: python3.14
    Tracing: Active
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable
        POWERTOOLS_SERVICE_NAME: order-service

Resources:
  # 1. The DynamoDB Table
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: order_id
        Type: String

  # 2. Create OrderApi Function
  OrderApiFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: .
        Handler: src.handlers.api.lambda_handler
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref OrdersTable
        Events:
          CreateOrder:
            Type: Api
            Properties:
              Path: /orders
              Method: post
          ProcessEvent:
            Type: Api
            Properties:
              Path: /orders/{order_id}/events
              Method: post
          GetOrder:
            Type: Api 
            Properties:
              Path: /orders/{order_id}
              Method: get

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"