AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order State Machine API

Globals:
  Function:
    Timeout: 15
    MemorySize: 512
    Runtime: python3.14
    Tracing: Active
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  # 1. The DynamoDB Table
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: order_id
        Type: String

  # 2. Create Order Function
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.create_order.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /orders
            Method: post

  # 3. Process Event Function
  ProcessEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.process_event.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        ProcessEvent:
          Type: Api
          Properties:
            Path: /orders/{order_id}/events
            Method: post

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"