"""
Main entry point for the Order API Lambda function.

This module uses AWS Lambda Powertools to provide a unified entry point
for all API Gateway requests, delegating routing to specialized handlers
in create_order.py and process_event.py.
"""
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.event_handler import APIGatewayRestResolver
from src.handlers.create_order import router as create_order_router
from src.handlers.process_event import router as process_event_router

logger = Logger()
tracer = Tracer()

# Initialize the main App
app = APIGatewayRestResolver()

# Register the routes
app.include_router(create_order_router)
app.include_router(process_event_router)

@logger.inject_lambda_context
@tracer.capture_lambda_handler
def lambda_handler(event, context):
    """
    AWS Lambda entry point for API Gateway events.

    This function resolves incoming HTTP requests to their corresponding
    route handlers defined in the included routers.

    Args:
        event: The AWS Lambda event object containing request data.
        context: The AWS Lambda context object containing execution environment info.

    Returns:
        The HTTP response generated by the resolved router.
    """
    return app.resolve(event, context)